name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: "MINGW64"

      - name: Install Make
        run: mingw-get install -y mingw64/mingw-w64-x86_64-make

      - name: Build
        run: make
